# Generated by Django 3.0.6 on 2020-06-13 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ppl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sid', models.CharField(max_length=50, unique=True)),
                ('grade', models.CharField(max_length=50)),
                ('pnum', models.CharField(max_length=50)),
                ('rnum', models.CharField(max_length=50)),
                ('lineuid', models.CharField(max_length=50, null=True)),
                ('secret', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
