# Generated by Django 3.0.6 on 2020-06-13 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('un', models.CharField(max_length=100)),
                ('pw', models.CharField(max_length=500)),
                ('lvl', models.IntegerField()),
            ],
        ),
    ]
