# Generated by Django 3.0.6 on 2020-06-13 15:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_acc'),
    ]

    operations = [
        migrations.AddField(
            model_name='acc',
            name='s',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
