# Generated by Django 3.0.6 on 2020-06-13 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_acc_s'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acc',
            name='s',
            field=models.BinaryField(max_length=100),
        ),
    ]
