# Generated by Django 3.0.6 on 2020-06-13 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20200613_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acc',
            name='s',
            field=models.BinaryField(),
        ),
    ]
